"""empty message

Revision ID: 925d141efeae
Revises: d6082ff8e400
Create Date: 2017-11-30 20:21:33.039380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925d141efeae'
down_revision = 'd6082ff8e400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
